const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIPv4() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal && iface.address) {
        // ignore APIPA addresses
        if (!iface.address.startsWith('169.')) return iface.address;
      }
    }
  }
  return null;
}

function writeApiFile(ip, port = 5000) {
  const content = `// Auto-generated by scripts/set-api-url.js\nexport const API_URL = 'http://${ip}:${port}';\n`;
  const target = path.resolve(__dirname, '..', 'constants', 'api.ts');
  fs.writeFileSync(target, content, { encoding: 'utf8' });
  console.log(`Wrote API_URL -> http://${ip}:${port} in ${target}`);
}

const ip = getLocalIPv4();
if (!ip) {
  console.error('Could not detect a local IPv4 address. You can pass it manually as the first argument.');
  process.exit(1);
}

const port = process.argv[2] || process.env.API_PORT || 5000;
writeApiFile(ip, port);
