/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Snackbar`; params?: Router.UnknownInputParams; } | { pathname: `/partner/login`; params?: Router.UnknownInputParams; } | { pathname: `/partner/order-details`; params?: Router.UnknownInputParams; } | { pathname: `/partner/orders`; params?: Router.UnknownInputParams; } | { pathname: `/partner/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/enter-code`; params?: Router.UnknownInputParams; } | { pathname: `/user/login`; params?: Router.UnknownInputParams; } | { pathname: `/user/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/status`; params?: Router.UnknownInputParams; } | { pathname: `/user/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/token`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Snackbar`; params?: Router.UnknownOutputParams; } | { pathname: `/partner/login`; params?: Router.UnknownOutputParams; } | { pathname: `/partner/order-details`; params?: Router.UnknownOutputParams; } | { pathname: `/partner/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/partner/register`; params?: Router.UnknownOutputParams; } | { pathname: `/user/enter-code`; params?: Router.UnknownOutputParams; } | { pathname: `/user/login`; params?: Router.UnknownOutputParams; } | { pathname: `/user/register`; params?: Router.UnknownOutputParams; } | { pathname: `/user/status`; params?: Router.UnknownOutputParams; } | { pathname: `/user/tracking`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/api`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/token`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Snackbar${`?${string}` | `#${string}` | ''}` | `/partner/login${`?${string}` | `#${string}` | ''}` | `/partner/order-details${`?${string}` | `#${string}` | ''}` | `/partner/orders${`?${string}` | `#${string}` | ''}` | `/partner/register${`?${string}` | `#${string}` | ''}` | `/user/enter-code${`?${string}` | `#${string}` | ''}` | `/user/login${`?${string}` | `#${string}` | ''}` | `/user/register${`?${string}` | `#${string}` | ''}` | `/user/status${`?${string}` | `#${string}` | ''}` | `/user/tracking${`?${string}` | `#${string}` | ''}` | `/utils/api${`?${string}` | `#${string}` | ''}` | `/utils/token${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Snackbar`; params?: Router.UnknownInputParams; } | { pathname: `/partner/login`; params?: Router.UnknownInputParams; } | { pathname: `/partner/order-details`; params?: Router.UnknownInputParams; } | { pathname: `/partner/orders`; params?: Router.UnknownInputParams; } | { pathname: `/partner/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/enter-code`; params?: Router.UnknownInputParams; } | { pathname: `/user/login`; params?: Router.UnknownInputParams; } | { pathname: `/user/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/status`; params?: Router.UnknownInputParams; } | { pathname: `/user/tracking`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/token`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
